language: node_js
node_js:
  - "8"
install:
  - "npm install"
script: "jest"
notifications:
  slack:
    secure: qagL3VMS4GdorCszy7qtslt3155dAkpCo0JtV6JIxV1VIAGzFJWBaM5zBMzX2OgcleJx5K2sBATypsQZCGQ0Z2OmV7v6yZXs63xn+VzFkG9flzGukXpWGbKHEczJoclFVrNdt4RrPIsFdioUsraQX+HTDw0ptmc9uTK5quxgTbD6pFcDVwqR0XnQoZElIb4zPVabb5KB4Dc5oGHf+RPsl7j2tahOMxeRLdSFEzIISUw7UimWd8LsRYyM20yARUgMSK9ErzLqDAWMBdu+SeqRbjNPZ6fSb+6261kO0NMZHSOjLZKwUE8CE0O1v+90eXJS960w147b3oxm5+T1AOe+idgTEzzbUsua7Ktb1HH0Uo54psasphTDET8Z2d23FUJ7tw9kVUyan4MBwPeM5MWHpaoLi1eQkjtouFEGHLfYimIhM+iAkpKX9S+x80LqCWLtmHope233U5O0bNHpCn2/nORtRhHmHmZIo2Sgvc5UFUPmHwUV/v4IG4U+4bDHFqLjgrXwHnWoMXc5f8lDzkwlJIx8gqQiNJSgLve+6f3fOJWFaeSm0g4nMsEqKnioeGTKDHuL8pO94Q1Lonap2JYC8FV1MO8zhEtoWZLDY0qX7vhCZRLbkBK4QGC7lBGiX+GADCk7PEnoIOUMioLeaj40Vs0xUloC0ETD8tOXQozckeA=
